** TDT4255 Exercise 0: Introduction to Chisel and HDLs (20 Points)

This is the exercise 0 chisel intro for the TDT4255 course at NTNU. You may also be here if you are taking TDT4295.

The main content of this repository was originally created by [[https://github.com/PeterAaser][Peter Aaser]]. It is now maintained by [[https://github.com/josephRog][Joseph Rogers]]

There are several separate modules for you to read through before you will be ready
to start writing code.
However, if you just want to get started right away you can skip the introduction
to hardware description languages, and jump straight to the [[./introduction.org][Intro to chisel]] which
covers the practical steps necessary to build your first circuits.
In order to get started you should go through the introductory material:
- [[./hdl.org][Introduction to hardware description languages]]
- [[./introduction.org][Introduction to hardware chisel]]

*** Points Breakdown
This exercise is worth a total of 20 points. These are all split between various tests in the introductory section to shown that the Chisel toolchain has been set up correctly, and that you have basic understanding of some of the language concepts. The points are given out as follows

9 Tests from [[./introduction.org][the introduction]], 1 point each:
- FirstTest
- MyIncrementTest
- MyIncrementManyTest
- MyVecSpec
- MyVecAltSpec
- InvalidSpec
- DelaySpec
- PrintfExampleSpec
- EvilPrintfSpec
1 additional point for getting everything correct.


Once you are finished with the initial part of this exercise, you have to create a [[./exercise.org][matrix multplier]] in hardware.
- 2 point for VectorSpec
- 1 point for MatrixSpec
- 2 points for DotProdSpec
- 5 points for the complete Matrix multiplication

To get checked off for all of your points, show that these tests are working during one of the lab sessions.

